name: Glitch
favicon: null
layout_spectrum: 0
typography_spectrum: 0.82764
title: Glitch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08080a'
    - '#23fe26'
    - '#0100fb'
    - '#fdfc0c'
    - '#f10206'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
